spring:
  application:
    name: fisheriz-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/naren1996/fiseriz-config-server.git
          skipSslValidation: true
  #spring.cloud.config.server.native:searchLocations=file:///${user.dir}/cloud-configuration-repository

server:
  port: 8888

